/*
 * fuzzygen — DICRON kernel test fuzzer
 *
 * Generates randomized test scenarios for kernel subsystems.
 * Output is a single C file placed in kernel/src/tests/test_fuzz.c
 * that auto-registers with the ktest framework.
 *
 * Usage: fuzzygen [count]
 *   count: number of fuzz scenarios to generate (1–100, default 50)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdint.h>
#include "fuzzygen.h"

static FILE *out;

/* ── random helpers ── */

static uint64_t rand_u64(void)
{
	return ((uint64_t)rand() << 32) | (uint64_t)rand();
}

static uint64_t rand_range(uint64_t lo, uint64_t hi)
{
	if (lo >= hi) return lo;
	return lo + (rand_u64() % (hi - lo + 1));
}

static int rand_order(void)
{
	/* PMM orders 0–10, bias toward lower */
	int r = rand() % 100;
	if (r < 50) return 0;
	if (r < 70) return 1;
	if (r < 85) return 2;
	if (r < 93) return 3;
	return (int)(4 + rand() % 7);
}

/* ── emitters ── */

static void emit_header(int count, unsigned seed)
{
	fprintf(out,
		"/* AUTO-GENERATED by fuzzygen — do not edit */\n"
		"/* Seed: %u  Scenarios: %d */\n\n"
		"#include \"ktest.h\"\n"
		"#include \"mm/pmm.h\"\n"
		"#include \"mm/slab.h\"\n"
		"#include \"mm/kheap.h\"\n"
		"#include \"lib/string.h\"\n"
		"#include <stdint.h>\n"
		"#include <stddef.h>\n\n",
		seed, count);
}

static void emit_pmm_fuzz(int id)
{
	int n_allocs = (int)rand_range(2, 32);
	int order = rand_order();

	fprintf(out,
		"static void fuzz_pmm_%d(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: PMM scenario %d\");\n"
		"\tsize_t before = pmm_free_pages_count();\n"
		"\tvoid *pages[%d];\n"
		"\tint ok = 1;\n"
		"\tfor (int i = 0; i < %d; i++) {\n"
		"\t\tpages[i] = pmm_alloc_pages(%d);\n"
		"\t\tif (!pages[i]) { ok = 0; break; }\n"
		"\t}\n"
		"\tKTEST_TRUE(ok, \"fuzz_pmm_%d: all allocs succeeded\");\n",
		id, id, n_allocs, n_allocs, order, id);

	/* Random free order: reverse, random-even-odd, or sequential */
	int pattern = rand() % 3;
	if (pattern == 0) {
		fprintf(out,
			"\tfor (int i = %d - 1; i >= 0; i--)\n"
			"\t\tpmm_free_pages(pages[i], %d);\n",
			n_allocs, order);
	} else if (pattern == 1) {
		fprintf(out,
			"\tfor (int i = 0; i < %d; i += 2)\n"
			"\t\tpmm_free_pages(pages[i], %d);\n"
			"\tfor (int i = 1; i < %d; i += 2)\n"
			"\t\tpmm_free_pages(pages[i], %d);\n",
			n_allocs, order, n_allocs, order);
	} else {
		fprintf(out,
			"\tfor (int i = 0; i < %d; i++)\n"
			"\t\tpmm_free_pages(pages[i], %d);\n",
			n_allocs, order);
	}

	fprintf(out,
		"\tKTEST_EQ(pmm_free_pages_count(), before, "
		"\"fuzz_pmm_%d: zero leak\");\n"
		"}\n\n", id);
}

static void emit_slab_fuzz(int id)
{
	int obj_size = (int)rand_range(8, 512);
	int n_objs = (int)rand_range(4, 64);
	uint8_t pattern = (uint8_t)(rand() & 0xFF);

	fprintf(out,
		"static void fuzz_slab_%d(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: slab scenario %d\");\n"
		"\tstruct kmem_cache *c = kmem_cache_create(\"fuzz-%d\", %d, NULL, NULL);\n"
		"\tKTEST_NOT_NULL(c, \"fuzz_slab_%d: cache created\");\n"
		"\tvoid *objs[%d];\n"
		"\tfor (int i = 0; i < %d; i++) {\n"
		"\t\tobjs[i] = kmem_cache_alloc(c);\n"
		"\t\tKTEST_NOT_NULL(objs[i], \"fuzz_slab_%d: alloc\");\n"
		"\t\tmemset(objs[i], 0x%02X, %d);\n"
		"\t}\n",
		id, id, id, obj_size, id, n_objs, n_objs, id, pattern, obj_size);

	fprintf(out,
		"\tint ok = 1;\n"
		"\tfor (int i = 0; i < %d; i++) {\n"
		"\t\tuint8_t *p = objs[i];\n"
		"\t\tfor (int j = 0; j < %d; j++)\n"
		"\t\t\tif (p[j] != 0x%02X) ok = 0;\n"
		"\t}\n"
		"\tKTEST_TRUE(ok, \"fuzz_slab_%d: patterns intact\");\n"
		"\tfor (int i = 0; i < %d; i++)\n"
		"\t\tkmem_cache_free(c, objs[i]);\n"
		"}\n\n",
		n_objs, obj_size, pattern, id, n_objs);
}

static void emit_kheap_fuzz(int id)
{
	int n = (int)rand_range(4, 40);
	/* Generate random sizes */
	fprintf(out,
		"static void fuzz_kheap_%d(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: kheap scenario %d\");\n"
		"\tstatic const size_t sizes[] = {",
		id, id);

	for (int i = 0; i < n; i++) {
		size_t sz = (size_t)rand_range(1, 8192);
		fprintf(out, "%s%zu", i ? ", " : "", sz);
	}
	fprintf(out, "};\n"
		"\tint count = (int)(sizeof(sizes) / sizeof(sizes[0]));\n"
		"\tvoid *ptrs[%d];\n"
		"\tfor (int i = 0; i < count; i++) {\n"
		"\t\tptrs[i] = kmalloc(sizes[i]);\n"
		"\t\tKTEST_NOT_NULL(ptrs[i], \"fuzz_kheap_%d: alloc\");\n"
		"\t\tmemset(ptrs[i], (int)(i & 0xFF), sizes[i]);\n"
		"\t}\n",
		n, id);

	/* Verify and free */
	fprintf(out,
		"\tint ok = 1;\n"
		"\tfor (int i = 0; i < count; i++) {\n"
		"\t\tuint8_t *p = ptrs[i];\n"
		"\t\tfor (size_t j = 0; j < sizes[i]; j++)\n"
		"\t\t\tif (p[j] != (uint8_t)(i & 0xFF)) ok = 0;\n"
		"\t\tkfree(ptrs[i]);\n"
		"\t}\n"
		"\tKTEST_TRUE(ok, \"fuzz_kheap_%d: all patterns intact\");\n"
		"}\n\n", id);
}

static void emit_string_fuzz(int id)
{
	int len = (int)rand_range(1, 128);
	uint8_t fill = (uint8_t)(rand() & 0xFF);
	if (fill == 0) fill = 1; /* avoid null terminator in middle */

	fprintf(out,
		"static void fuzz_string_%d(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: string scenario %d\");\n"
		"\tchar buf[%d];\n"
		"\tmemset(buf, 0x%02X, %d);\n"
		"\tint ok = 1;\n"
		"\tfor (int i = 0; i < %d; i++)\n"
		"\t\tif ((unsigned char)buf[i] != 0x%02X) ok = 0;\n"
		"\tKTEST_TRUE(ok, \"fuzz_string_%d: memset pattern\");\n"
		"\tmemset(buf, 0, %d);\n"
		"\tok = 1;\n"
		"\tfor (int i = 0; i < %d; i++)\n"
		"\t\tif (buf[i] != 0) ok = 0;\n"
		"\tKTEST_TRUE(ok, \"fuzz_string_%d: memset zero\");\n",
		id, id, len, fill, len, len, fill, id, len, len, id);

	/* memcpy round-trip */
	fprintf(out,
		"\tchar src[%d], dst[%d];\n"
		"\tfor (int i = 0; i < %d; i++) src[i] = (char)(i & 0x7F);\n"
		"\tmemcpy(dst, src, %d);\n"
		"\tKTEST_EQ(memcmp(src, dst, %d), 0, \"fuzz_string_%d: memcpy\");\n"
		"}\n\n",
		len, len, len, len, len, id);
}

static void emit_math_fuzz(int id)
{
	int64_t a = (int64_t)rand_range(0, 1000000);
	int64_t b = (int64_t)rand_range(1, 1000000); /* avoid div by zero */
	int64_t sum = a + b;
	int64_t diff = a - b;
	int64_t prod = a * b;
	int64_t quot = a / b;
	int64_t rem  = a % b;

	fprintf(out,
		"static void fuzz_math_%d(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: math scenario %d\");\n"
		"\tlong long a = %lldLL, b = %lldLL;\n"
		"\tKTEST_EQ(a + b, %lldLL, \"fuzz_math_%d: add\");\n"
		"\tKTEST_EQ(a - b, %lldLL, \"fuzz_math_%d: sub\");\n"
		"\tKTEST_EQ(a * b, %lldLL, \"fuzz_math_%d: mul\");\n"
		"\tKTEST_EQ(a / b, %lldLL, \"fuzz_math_%d: div\");\n"
		"\tKTEST_EQ(a %% b, %lldLL, \"fuzz_math_%d: mod\");\n"
		"}\n\n",
		id, id,
		(long long)a, (long long)b,
		(long long)sum, id,
		(long long)diff, id,
		(long long)prod, id,
		(long long)quot, id,
		(long long)rem, id);
}

/* Category distribution weights */
static const int category_weights[FUZZ_CATEGORY_COUNT] = {
	25,  /* PMM */
	20,  /* SLAB */
	25,  /* KHEAP */
	15,  /* STRING */
	15,  /* MATH */
	0    /* SPINLOCK — hard to fuzz in single-threaded codegen */
};

static int pick_category(void)
{
	int total = 0;
	for (int i = 0; i < FUZZ_CATEGORY_COUNT; i++)
		total += category_weights[i];
	int r = rand() % total;
	int cum = 0;
	for (int i = 0; i < FUZZ_CATEGORY_COUNT; i++) {
		cum += category_weights[i];
		if (r < cum) return i;
	}
	return 0;
}

static void emit_scenario(int id, int category)
{
	switch (category) {
	case FUZZ_PMM:     emit_pmm_fuzz(id);    break;
	case FUZZ_SLAB:    emit_slab_fuzz(id);   break;
	case FUZZ_KHEAP:   emit_kheap_fuzz(id);  break;
	case FUZZ_STRING:  emit_string_fuzz(id);  break;
	case FUZZ_MATH:    emit_math_fuzz(id);    break;
	default:           emit_math_fuzz(id);    break;
	}
}

static void emit_runner(int count, int *categories)
{
	fprintf(out,
		"KTEST_REGISTER(ktest_fuzz, \"fuzz: generated scenarios\", KTEST_CAT_BOOT)\n"
		"static void ktest_fuzz(void)\n{\n"
		"\tKTEST_BEGIN(\"fuzz: generated scenarios\");\n");

	for (int i = 0; i < count; i++) {
		fprintf(out, "\tfuzz_%s_%d();\n",
			fuzz_category_names[categories[i]], i);
	}

	fprintf(out, "}\n");
}

int main(int argc, char **argv)
{
	int count = 50;
	if (argc > 1) {
		count = atoi(argv[1]);
		if (count < FUZZ_MIN_TESTS) count = FUZZ_MIN_TESTS;
		if (count > FUZZ_MAX_TESTS) count = FUZZ_MAX_TESTS;
	}

	unsigned seed = (unsigned)time(NULL);
	srand(seed);

	const char *outpath = FUZZ_OUTPUT_DIR "/test_fuzz.c";
	out = fopen(outpath, "w");
	if (!out) {
		fprintf(stderr, "fuzzygen: cannot open %s for writing\n", outpath);
		return 1;
	}

	emit_header(count, seed);

	int categories[FUZZ_MAX_TESTS];
	for (int i = 0; i < count; i++) {
		categories[i] = pick_category();
		emit_scenario(i, categories[i]);
	}

	emit_runner(count, categories);

	fclose(out);
	printf("fuzzygen: generated %d scenarios (seed=%u) -> %s\n",
	       count, seed, outpath);
	return 0;
}
