#!/usr/bin/env python3
"""
DICRON kernel configuration generator.

Usage:
  python3 tools/genconfig.py defconfig     — generate default .config
  python3 tools/genconfig.py menuconfig    — interactive menu
  python3 tools/genconfig.py oldconfig     — update .config with new defaults
  python3 tools/genconfig.py --set K=V ... — set config values from CLI
  python3 tools/genconfig.py genheader     — regenerate autoconf.h from .config
"""

import sys
import os

# Ensure kconfiglib is available
try:
    from kconfiglib import Kconfig, BOOL, TRISTATE, STRING, INT, HEX
    from menuconfig import menuconfig as _menuconfig
except ImportError:
    print("Error: kconfiglib not installed. Run: pip install kconfiglib")
    sys.exit(1)

KCONFIG_FILE = "Kconfig"
DOT_CONFIG = ".config"
AUTOCONF_H = "kernel/include/generated/autoconf.h"


def load_kconfig():
    if not os.path.exists(KCONFIG_FILE):
        print(f"Error: {KCONFIG_FILE} not found")
        sys.exit(1)
    return Kconfig(KCONFIG_FILE, warn=False)


def write_autoconf(kconf):
    """Generate a C header with #define CONFIG_xxx for each enabled option."""
    os.makedirs(os.path.dirname(AUTOCONF_H), exist_ok=True)
    with open(AUTOCONF_H, "w") as f:
        f.write("/* Auto-generated by tools/genconfig.py — DO NOT EDIT */\n")
        f.write("#ifndef _DICRON_AUTOCONF_H\n")
        f.write("#define _DICRON_AUTOCONF_H\n\n")

        for sym in kconf.unique_defined_syms:
            if sym.type in (BOOL, TRISTATE):
                if sym.str_value == "y":
                    f.write(f"#define CONFIG_{sym.name} 1\n")
                # Don't write anything for 'n' — absence means disabled
            elif sym.type == STRING:
                f.write(f'#define CONFIG_{sym.name} "{sym.str_value}"\n')
            elif sym.type in (INT, HEX):
                f.write(f"#define CONFIG_{sym.name} {sym.str_value}\n")

        f.write("\n#endif\n")
    print(f"  CONF    {AUTOCONF_H}")


def write_config_mk(kconf):
    """Generate .config with Makefile-compatible CONFIG_xxx=y lines."""
    kconf.write_config(DOT_CONFIG)
    print(f"  CONF    {DOT_CONFIG}")


def cmd_defconfig():
    kconf = load_kconfig()
    # All defaults are already set by Kconfig 'default' clauses
    write_config_mk(kconf)
    write_autoconf(kconf)


def cmd_menuconfig():
    kconf = load_kconfig()
    if os.path.exists(DOT_CONFIG):
        kconf.load_config(DOT_CONFIG)
    _menuconfig(kconf)
    write_config_mk(kconf)
    write_autoconf(kconf)


def cmd_oldconfig():
    kconf = load_kconfig()
    if os.path.exists(DOT_CONFIG):
        kconf.load_config(DOT_CONFIG)
    write_config_mk(kconf)
    write_autoconf(kconf)


def cmd_genheader():
    kconf = load_kconfig()
    if os.path.exists(DOT_CONFIG):
        kconf.load_config(DOT_CONFIG)
    write_autoconf(kconf)


def cmd_set(args):
    kconf = load_kconfig()
    if os.path.exists(DOT_CONFIG):
        kconf.load_config(DOT_CONFIG)

    for arg in args:
        if "=" not in arg:
            print(f"Error: expected K=V, got '{arg}'")
            sys.exit(1)
        key, val = arg.split("=", 1)
        key = key.removeprefix("CONFIG_")
        sym = kconf.syms.get(key)
        if not sym:
            print(f"Warning: unknown symbol CONFIG_{key}")
            continue
        sym.set_value(val)
        print(f"  SET     CONFIG_{key}={val}")

    write_config_mk(kconf)
    write_autoconf(kconf)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "defconfig":
        cmd_defconfig()
    elif cmd == "menuconfig":
        cmd_menuconfig()
    elif cmd == "oldconfig":
        cmd_oldconfig()
    elif cmd == "genheader":
        cmd_genheader()
    elif cmd == "--set":
        cmd_set(sys.argv[2:])
    else:
        print(f"Unknown command: {cmd}")
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
