/* AUTO-GENERATED by fuzzygen — do not edit */
/* Seed: 1774306461  Scenarios: 100 */

#include "ktest.h"
#include "mm/pmm.h"
#include "mm/slab.h"
#include "mm/kheap.h"
#include "lib/string.h"
#include <stdint.h>
#include <stddef.h>

static void fuzz_slab_0(void)
{
	KTEST_BEGIN("fuzz: slab scenario 0");
	struct kmem_cache *c = kmem_cache_create("fuzz-0", 366, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_0: cache created");
	void *objs[49];
	for (int i = 0; i < 49; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_0: alloc");
		memset(objs[i], 0xFB, 366);
	}
	int ok = 1;
	for (int i = 0; i < 49; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 366; j++)
			if (p[j] != 0xFB) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_0: patterns intact");
	for (int i = 0; i < 49; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_1(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 1");
	static const size_t sizes[] = {2812, 8122, 2795, 1500, 298, 5069, 7211, 5969, 2079, 7963, 5849, 496, 1502, 2645, 8085, 612, 7264, 73, 5138, 4662, 5684, 3908, 3954, 2767, 5078, 6718, 113};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[27];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_1: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_1: all patterns intact");
}

static void fuzz_kheap_2(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 2");
	static const size_t sizes[] = {3164, 7566, 5290, 869, 2150, 2776, 7395, 1213, 3925, 4694, 489, 2494, 1059};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[13];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_2: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_2: all patterns intact");
}

static void fuzz_pmm_3(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 3");
	size_t before = pmm_free_pages_count();
	void *pages[6];
	int ok = 1;
	for (int i = 0; i < 6; i++) {
		pages[i] = pmm_alloc_pages(3);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_3: all allocs succeeded");
	for (int i = 6 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 3);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_3: zero leak");
}

static void fuzz_slab_4(void)
{
	KTEST_BEGIN("fuzz: slab scenario 4");
	struct kmem_cache *c = kmem_cache_create("fuzz-4", 252, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_4: cache created");
	void *objs[14];
	for (int i = 0; i < 14; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_4: alloc");
		memset(objs[i], 0x7E, 252);
	}
	int ok = 1;
	for (int i = 0; i < 14; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 252; j++)
			if (p[j] != 0x7E) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_4: patterns intact");
	for (int i = 0; i < 14; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_5(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 5");
	static const size_t sizes[] = {6116, 6882, 6957, 6059, 5817, 105, 5094, 1138, 7826, 6231, 833, 6098, 4725, 404, 3802, 703, 3314, 7044, 7486, 4766, 7469, 3222, 7469, 2330, 442, 4290};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[26];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_5: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_5: all patterns intact");
}

static void fuzz_pmm_6(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 6");
	size_t before = pmm_free_pages_count();
	void *pages[17];
	int ok = 1;
	for (int i = 0; i < 17; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_6: all allocs succeeded");
	for (int i = 0; i < 17; i += 2)
		pmm_free_pages(pages[i], 0);
	for (int i = 1; i < 17; i += 2)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_6: zero leak");
}

static void fuzz_string_7(void)
{
	KTEST_BEGIN("fuzz: string scenario 7");
	char buf[105];
	memset(buf, 0x10, 105);
	int ok = 1;
	for (int i = 0; i < 105; i++)
		if ((unsigned char)buf[i] != 0x10) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_7: memset pattern");
	memset(buf, 0, 105);
	ok = 1;
	for (int i = 0; i < 105; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_7: memset zero");
	char src[105], dst[105];
	for (int i = 0; i < 105; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 105);
	KTEST_EQ(memcmp(src, dst, 105), 0, "fuzz_string_7: memcpy");
}

static void fuzz_kheap_8(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 8");
	static const size_t sizes[] = {327, 5511, 3710, 4729, 6955, 7356, 4118, 5140, 1860, 5833, 3433, 2516, 4730, 4271, 3684, 92, 3020, 3630, 7687, 1523, 8116, 4487, 2178, 408};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[24];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_8: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_8: all patterns intact");
}

static void fuzz_slab_9(void)
{
	KTEST_BEGIN("fuzz: slab scenario 9");
	struct kmem_cache *c = kmem_cache_create("fuzz-9", 187, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_9: cache created");
	void *objs[55];
	for (int i = 0; i < 55; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_9: alloc");
		memset(objs[i], 0x37, 187);
	}
	int ok = 1;
	for (int i = 0; i < 55; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 187; j++)
			if (p[j] != 0x37) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_9: patterns intact");
	for (int i = 0; i < 55; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_10(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 10");
	static const size_t sizes[] = {36, 4617, 511, 7275, 4064, 5607, 7334, 4153, 157, 2004, 408, 4261, 1710, 5679, 6128, 829, 1666, 2227, 5880, 96, 7120, 5979, 1372, 6087, 1940, 3117, 5938, 802, 1356, 7542, 7727, 5454, 5624, 3375, 797, 5061};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[36];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_10: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_10: all patterns intact");
}

static void fuzz_string_11(void)
{
	KTEST_BEGIN("fuzz: string scenario 11");
	char buf[31];
	memset(buf, 0x60, 31);
	int ok = 1;
	for (int i = 0; i < 31; i++)
		if ((unsigned char)buf[i] != 0x60) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_11: memset pattern");
	memset(buf, 0, 31);
	ok = 1;
	for (int i = 0; i < 31; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_11: memset zero");
	char src[31], dst[31];
	for (int i = 0; i < 31; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 31);
	KTEST_EQ(memcmp(src, dst, 31), 0, "fuzz_string_11: memcpy");
}

static void fuzz_math_12(void)
{
	KTEST_BEGIN("fuzz: math scenario 12");
	long long a = 2559LL, b = 166981LL;
	KTEST_EQ(a + b, 169540LL, "fuzz_math_12: add");
	KTEST_EQ(a - b, -164422LL, "fuzz_math_12: sub");
	KTEST_EQ(a * b, 427304379LL, "fuzz_math_12: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_12: div");
	KTEST_EQ(a % b, 2559LL, "fuzz_math_12: mod");
}

static void fuzz_pmm_13(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 13");
	size_t before = pmm_free_pages_count();
	void *pages[32];
	int ok = 1;
	for (int i = 0; i < 32; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_13: all allocs succeeded");
	for (int i = 32 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_13: zero leak");
}

static void fuzz_slab_14(void)
{
	KTEST_BEGIN("fuzz: slab scenario 14");
	struct kmem_cache *c = kmem_cache_create("fuzz-14", 233, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_14: cache created");
	void *objs[54];
	for (int i = 0; i < 54; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_14: alloc");
		memset(objs[i], 0xA6, 233);
	}
	int ok = 1;
	for (int i = 0; i < 54; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 233; j++)
			if (p[j] != 0xA6) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_14: patterns intact");
	for (int i = 0; i < 54; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_pmm_15(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 15");
	size_t before = pmm_free_pages_count();
	void *pages[29];
	int ok = 1;
	for (int i = 0; i < 29; i++) {
		pages[i] = pmm_alloc_pages(4);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_15: all allocs succeeded");
	for (int i = 29 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 4);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_15: zero leak");
}

static void fuzz_slab_16(void)
{
	KTEST_BEGIN("fuzz: slab scenario 16");
	struct kmem_cache *c = kmem_cache_create("fuzz-16", 470, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_16: cache created");
	void *objs[17];
	for (int i = 0; i < 17; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_16: alloc");
		memset(objs[i], 0xFB, 470);
	}
	int ok = 1;
	for (int i = 0; i < 17; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 470; j++)
			if (p[j] != 0xFB) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_16: patterns intact");
	for (int i = 0; i < 17; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_17(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 17");
	static const size_t sizes[] = {5744, 6555, 1346, 5155, 3341, 3843, 6802, 1311};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[8];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_17: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_17: all patterns intact");
}

static void fuzz_string_18(void)
{
	KTEST_BEGIN("fuzz: string scenario 18");
	char buf[19];
	memset(buf, 0x5B, 19);
	int ok = 1;
	for (int i = 0; i < 19; i++)
		if ((unsigned char)buf[i] != 0x5B) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_18: memset pattern");
	memset(buf, 0, 19);
	ok = 1;
	for (int i = 0; i < 19; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_18: memset zero");
	char src[19], dst[19];
	for (int i = 0; i < 19; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 19);
	KTEST_EQ(memcmp(src, dst, 19), 0, "fuzz_string_18: memcpy");
}

static void fuzz_pmm_19(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 19");
	size_t before = pmm_free_pages_count();
	void *pages[21];
	int ok = 1;
	for (int i = 0; i < 21; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_19: all allocs succeeded");
	for (int i = 0; i < 21; i++)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_19: zero leak");
}

static void fuzz_slab_20(void)
{
	KTEST_BEGIN("fuzz: slab scenario 20");
	struct kmem_cache *c = kmem_cache_create("fuzz-20", 268, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_20: cache created");
	void *objs[24];
	for (int i = 0; i < 24; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_20: alloc");
		memset(objs[i], 0x6B, 268);
	}
	int ok = 1;
	for (int i = 0; i < 24; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 268; j++)
			if (p[j] != 0x6B) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_20: patterns intact");
	for (int i = 0; i < 24; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_21(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 21");
	static const size_t sizes[] = {4746, 772, 4706, 350, 6792, 4523, 5263, 5305, 3605, 6960, 3028, 1221, 3573, 6992, 4609, 4234, 1132, 2870, 924, 6192, 2179, 7625, 3522, 3322, 2623, 6386, 3095, 1526, 3552, 7292, 7810, 1131};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[32];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_21: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_21: all patterns intact");
}

static void fuzz_math_22(void)
{
	KTEST_BEGIN("fuzz: math scenario 22");
	long long a = 171571LL, b = 18926LL;
	KTEST_EQ(a + b, 190497LL, "fuzz_math_22: add");
	KTEST_EQ(a - b, 152645LL, "fuzz_math_22: sub");
	KTEST_EQ(a * b, 3247152746LL, "fuzz_math_22: mul");
	KTEST_EQ(a / b, 9LL, "fuzz_math_22: div");
	KTEST_EQ(a % b, 1237LL, "fuzz_math_22: mod");
}

static void fuzz_slab_23(void)
{
	KTEST_BEGIN("fuzz: slab scenario 23");
	struct kmem_cache *c = kmem_cache_create("fuzz-23", 60, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_23: cache created");
	void *objs[54];
	for (int i = 0; i < 54; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_23: alloc");
		memset(objs[i], 0x17, 60);
	}
	int ok = 1;
	for (int i = 0; i < 54; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 60; j++)
			if (p[j] != 0x17) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_23: patterns intact");
	for (int i = 0; i < 54; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_24(void)
{
	KTEST_BEGIN("fuzz: slab scenario 24");
	struct kmem_cache *c = kmem_cache_create("fuzz-24", 457, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_24: cache created");
	void *objs[64];
	for (int i = 0; i < 64; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_24: alloc");
		memset(objs[i], 0xD5, 457);
	}
	int ok = 1;
	for (int i = 0; i < 64; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 457; j++)
			if (p[j] != 0xD5) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_24: patterns intact");
	for (int i = 0; i < 64; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_math_25(void)
{
	KTEST_BEGIN("fuzz: math scenario 25");
	long long a = 990087LL, b = 244733LL;
	KTEST_EQ(a + b, 1234820LL, "fuzz_math_25: add");
	KTEST_EQ(a - b, 745354LL, "fuzz_math_25: sub");
	KTEST_EQ(a * b, 242306961771LL, "fuzz_math_25: mul");
	KTEST_EQ(a / b, 4LL, "fuzz_math_25: div");
	KTEST_EQ(a % b, 11155LL, "fuzz_math_25: mod");
}

static void fuzz_slab_26(void)
{
	KTEST_BEGIN("fuzz: slab scenario 26");
	struct kmem_cache *c = kmem_cache_create("fuzz-26", 213, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_26: cache created");
	void *objs[37];
	for (int i = 0; i < 37; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_26: alloc");
		memset(objs[i], 0xBC, 213);
	}
	int ok = 1;
	for (int i = 0; i < 37; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 213; j++)
			if (p[j] != 0xBC) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_26: patterns intact");
	for (int i = 0; i < 37; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_27(void)
{
	KTEST_BEGIN("fuzz: slab scenario 27");
	struct kmem_cache *c = kmem_cache_create("fuzz-27", 375, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_27: cache created");
	void *objs[34];
	for (int i = 0; i < 34; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_27: alloc");
		memset(objs[i], 0xC5, 375);
	}
	int ok = 1;
	for (int i = 0; i < 34; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 375; j++)
			if (p[j] != 0xC5) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_27: patterns intact");
	for (int i = 0; i < 34; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_pmm_28(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 28");
	size_t before = pmm_free_pages_count();
	void *pages[24];
	int ok = 1;
	for (int i = 0; i < 24; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_28: all allocs succeeded");
	for (int i = 24 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_28: zero leak");
}

static void fuzz_pmm_29(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 29");
	size_t before = pmm_free_pages_count();
	void *pages[3];
	int ok = 1;
	for (int i = 0; i < 3; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_29: all allocs succeeded");
	for (int i = 3 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_29: zero leak");
}

static void fuzz_slab_30(void)
{
	KTEST_BEGIN("fuzz: slab scenario 30");
	struct kmem_cache *c = kmem_cache_create("fuzz-30", 153, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_30: cache created");
	void *objs[51];
	for (int i = 0; i < 51; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_30: alloc");
		memset(objs[i], 0x0F, 153);
	}
	int ok = 1;
	for (int i = 0; i < 51; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 153; j++)
			if (p[j] != 0x0F) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_30: patterns intact");
	for (int i = 0; i < 51; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_31(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 31");
	static const size_t sizes[] = {1563, 768, 8101, 1573, 5938, 2960, 6276, 5034, 1077, 5062, 779, 5077, 4389, 1251, 766, 2563, 1751, 2228, 2212, 5189, 7189, 3151, 1372, 6833, 5777};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[25];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_31: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_31: all patterns intact");
}

static void fuzz_string_32(void)
{
	KTEST_BEGIN("fuzz: string scenario 32");
	char buf[28];
	memset(buf, 0x7F, 28);
	int ok = 1;
	for (int i = 0; i < 28; i++)
		if ((unsigned char)buf[i] != 0x7F) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_32: memset pattern");
	memset(buf, 0, 28);
	ok = 1;
	for (int i = 0; i < 28; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_32: memset zero");
	char src[28], dst[28];
	for (int i = 0; i < 28; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 28);
	KTEST_EQ(memcmp(src, dst, 28), 0, "fuzz_string_32: memcpy");
}

static void fuzz_pmm_33(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 33");
	size_t before = pmm_free_pages_count();
	void *pages[24];
	int ok = 1;
	for (int i = 0; i < 24; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_33: all allocs succeeded");
	for (int i = 24 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_33: zero leak");
}

static void fuzz_pmm_34(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 34");
	size_t before = pmm_free_pages_count();
	void *pages[10];
	int ok = 1;
	for (int i = 0; i < 10; i++) {
		pages[i] = pmm_alloc_pages(2);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_34: all allocs succeeded");
	for (int i = 0; i < 10; i++)
		pmm_free_pages(pages[i], 2);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_34: zero leak");
}

static void fuzz_slab_35(void)
{
	KTEST_BEGIN("fuzz: slab scenario 35");
	struct kmem_cache *c = kmem_cache_create("fuzz-35", 37, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_35: cache created");
	void *objs[28];
	for (int i = 0; i < 28; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_35: alloc");
		memset(objs[i], 0x91, 37);
	}
	int ok = 1;
	for (int i = 0; i < 28; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 37; j++)
			if (p[j] != 0x91) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_35: patterns intact");
	for (int i = 0; i < 28; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_pmm_36(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 36");
	size_t before = pmm_free_pages_count();
	void *pages[6];
	int ok = 1;
	for (int i = 0; i < 6; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_36: all allocs succeeded");
	for (int i = 0; i < 6; i++)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_36: zero leak");
}

static void fuzz_kheap_37(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 37");
	static const size_t sizes[] = {5264, 6499, 4279, 1228, 3974, 4724, 8109, 794, 453, 6252, 854, 6436, 5027, 6191, 2505, 3789, 4053, 283, 1041, 8112, 1699, 6117, 2260, 3585, 2531, 7659, 7785, 1235, 5591, 5610, 5562, 7671, 3301, 1562, 1271, 1163, 6123};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[37];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_37: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_37: all patterns intact");
}

static void fuzz_kheap_38(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 38");
	static const size_t sizes[] = {8168, 335, 2369, 1213, 4953, 5668, 3249, 1555, 5049, 7754, 4538, 6079, 5065, 3949, 5439, 1955, 7041, 7034, 6007, 1294, 5884, 6953};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[22];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_38: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_38: all patterns intact");
}

static void fuzz_pmm_39(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 39");
	size_t before = pmm_free_pages_count();
	void *pages[12];
	int ok = 1;
	for (int i = 0; i < 12; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_39: all allocs succeeded");
	for (int i = 12 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_39: zero leak");
}

static void fuzz_slab_40(void)
{
	KTEST_BEGIN("fuzz: slab scenario 40");
	struct kmem_cache *c = kmem_cache_create("fuzz-40", 253, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_40: cache created");
	void *objs[31];
	for (int i = 0; i < 31; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_40: alloc");
		memset(objs[i], 0x32, 253);
	}
	int ok = 1;
	for (int i = 0; i < 31; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 253; j++)
			if (p[j] != 0x32) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_40: patterns intact");
	for (int i = 0; i < 31; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_math_41(void)
{
	KTEST_BEGIN("fuzz: math scenario 41");
	long long a = 359028LL, b = 627417LL;
	KTEST_EQ(a + b, 986445LL, "fuzz_math_41: add");
	KTEST_EQ(a - b, -268389LL, "fuzz_math_41: sub");
	KTEST_EQ(a * b, 225260270676LL, "fuzz_math_41: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_41: div");
	KTEST_EQ(a % b, 359028LL, "fuzz_math_41: mod");
}

static void fuzz_pmm_42(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 42");
	size_t before = pmm_free_pages_count();
	void *pages[7];
	int ok = 1;
	for (int i = 0; i < 7; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_42: all allocs succeeded");
	for (int i = 0; i < 7; i++)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_42: zero leak");
}

static void fuzz_kheap_43(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 43");
	static const size_t sizes[] = {6299, 6513, 5675, 4930, 5588, 3017, 7086, 323, 4719, 5287, 7387};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[11];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_43: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_43: all patterns intact");
}

static void fuzz_string_44(void)
{
	KTEST_BEGIN("fuzz: string scenario 44");
	char buf[7];
	memset(buf, 0x79, 7);
	int ok = 1;
	for (int i = 0; i < 7; i++)
		if ((unsigned char)buf[i] != 0x79) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_44: memset pattern");
	memset(buf, 0, 7);
	ok = 1;
	for (int i = 0; i < 7; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_44: memset zero");
	char src[7], dst[7];
	for (int i = 0; i < 7; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 7);
	KTEST_EQ(memcmp(src, dst, 7), 0, "fuzz_string_44: memcpy");
}

static void fuzz_pmm_45(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 45");
	size_t before = pmm_free_pages_count();
	void *pages[3];
	int ok = 1;
	for (int i = 0; i < 3; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_45: all allocs succeeded");
	for (int i = 3 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_45: zero leak");
}

static void fuzz_string_46(void)
{
	KTEST_BEGIN("fuzz: string scenario 46");
	char buf[25];
	memset(buf, 0xB6, 25);
	int ok = 1;
	for (int i = 0; i < 25; i++)
		if ((unsigned char)buf[i] != 0xB6) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_46: memset pattern");
	memset(buf, 0, 25);
	ok = 1;
	for (int i = 0; i < 25; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_46: memset zero");
	char src[25], dst[25];
	for (int i = 0; i < 25; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 25);
	KTEST_EQ(memcmp(src, dst, 25), 0, "fuzz_string_46: memcpy");
}

static void fuzz_string_47(void)
{
	KTEST_BEGIN("fuzz: string scenario 47");
	char buf[79];
	memset(buf, 0x82, 79);
	int ok = 1;
	for (int i = 0; i < 79; i++)
		if ((unsigned char)buf[i] != 0x82) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_47: memset pattern");
	memset(buf, 0, 79);
	ok = 1;
	for (int i = 0; i < 79; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_47: memset zero");
	char src[79], dst[79];
	for (int i = 0; i < 79; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 79);
	KTEST_EQ(memcmp(src, dst, 79), 0, "fuzz_string_47: memcpy");
}

static void fuzz_kheap_48(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 48");
	static const size_t sizes[] = {5584, 229, 8136, 3691, 6218, 4013, 7628, 3763, 6602, 6941, 2925, 4549, 6776, 4912, 565, 2560, 6790, 3863, 7735, 3770, 2246, 7048, 6027, 2064, 6908, 6755, 4833, 7190, 6970, 6575};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[30];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_48: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_48: all patterns intact");
}

static void fuzz_slab_49(void)
{
	KTEST_BEGIN("fuzz: slab scenario 49");
	struct kmem_cache *c = kmem_cache_create("fuzz-49", 249, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_49: cache created");
	void *objs[52];
	for (int i = 0; i < 52; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_49: alloc");
		memset(objs[i], 0x91, 249);
	}
	int ok = 1;
	for (int i = 0; i < 52; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 249; j++)
			if (p[j] != 0x91) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_49: patterns intact");
	for (int i = 0; i < 52; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_50(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 50");
	static const size_t sizes[] = {3027, 2767, 7888, 451, 6511, 1029, 3448, 3962, 1666, 5336, 5759, 7694, 1976, 2238, 7667, 3657, 6350, 5116, 2678, 167, 2260, 125, 3864, 4073, 3271, 2911, 5894};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[27];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_50: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_50: all patterns intact");
}

static void fuzz_kheap_51(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 51");
	static const size_t sizes[] = {1583, 2103, 6469, 5250, 1527, 7376, 3269, 1159, 304, 135, 2746, 7660, 381, 1664, 7842, 5421, 4153, 133, 3934, 7128, 293, 4359, 6490, 8024, 4191, 2990, 5629, 2706, 2762, 609, 5709, 3644, 5359, 4098, 965, 6559, 1153, 4818, 51};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[39];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_51: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_51: all patterns intact");
}

static void fuzz_math_52(void)
{
	KTEST_BEGIN("fuzz: math scenario 52");
	long long a = 616958LL, b = 564752LL;
	KTEST_EQ(a + b, 1181710LL, "fuzz_math_52: add");
	KTEST_EQ(a - b, 52206LL, "fuzz_math_52: sub");
	KTEST_EQ(a * b, 348428264416LL, "fuzz_math_52: mul");
	KTEST_EQ(a / b, 1LL, "fuzz_math_52: div");
	KTEST_EQ(a % b, 52206LL, "fuzz_math_52: mod");
}

static void fuzz_pmm_53(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 53");
	size_t before = pmm_free_pages_count();
	void *pages[8];
	int ok = 1;
	for (int i = 0; i < 8; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_53: all allocs succeeded");
	for (int i = 0; i < 8; i++)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_53: zero leak");
}

static void fuzz_slab_54(void)
{
	KTEST_BEGIN("fuzz: slab scenario 54");
	struct kmem_cache *c = kmem_cache_create("fuzz-54", 447, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_54: cache created");
	void *objs[5];
	for (int i = 0; i < 5; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_54: alloc");
		memset(objs[i], 0x66, 447);
	}
	int ok = 1;
	for (int i = 0; i < 5; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 447; j++)
			if (p[j] != 0x66) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_54: patterns intact");
	for (int i = 0; i < 5; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_55(void)
{
	KTEST_BEGIN("fuzz: slab scenario 55");
	struct kmem_cache *c = kmem_cache_create("fuzz-55", 33, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_55: cache created");
	void *objs[16];
	for (int i = 0; i < 16; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_55: alloc");
		memset(objs[i], 0xA0, 33);
	}
	int ok = 1;
	for (int i = 0; i < 16; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 33; j++)
			if (p[j] != 0xA0) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_55: patterns intact");
	for (int i = 0; i < 16; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_kheap_56(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 56");
	static const size_t sizes[] = {1140, 6742, 5911, 6832};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[4];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_56: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_56: all patterns intact");
}

static void fuzz_math_57(void)
{
	KTEST_BEGIN("fuzz: math scenario 57");
	long long a = 229610LL, b = 871494LL;
	KTEST_EQ(a + b, 1101104LL, "fuzz_math_57: add");
	KTEST_EQ(a - b, -641884LL, "fuzz_math_57: sub");
	KTEST_EQ(a * b, 200103737340LL, "fuzz_math_57: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_57: div");
	KTEST_EQ(a % b, 229610LL, "fuzz_math_57: mod");
}

static void fuzz_string_58(void)
{
	KTEST_BEGIN("fuzz: string scenario 58");
	char buf[1];
	memset(buf, 0xD9, 1);
	int ok = 1;
	for (int i = 0; i < 1; i++)
		if ((unsigned char)buf[i] != 0xD9) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_58: memset pattern");
	memset(buf, 0, 1);
	ok = 1;
	for (int i = 0; i < 1; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_58: memset zero");
	char src[1], dst[1];
	for (int i = 0; i < 1; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 1);
	KTEST_EQ(memcmp(src, dst, 1), 0, "fuzz_string_58: memcpy");
}

static void fuzz_string_59(void)
{
	KTEST_BEGIN("fuzz: string scenario 59");
	char buf[55];
	memset(buf, 0x63, 55);
	int ok = 1;
	for (int i = 0; i < 55; i++)
		if ((unsigned char)buf[i] != 0x63) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_59: memset pattern");
	memset(buf, 0, 55);
	ok = 1;
	for (int i = 0; i < 55; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_59: memset zero");
	char src[55], dst[55];
	for (int i = 0; i < 55; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 55);
	KTEST_EQ(memcmp(src, dst, 55), 0, "fuzz_string_59: memcpy");
}

static void fuzz_string_60(void)
{
	KTEST_BEGIN("fuzz: string scenario 60");
	char buf[125];
	memset(buf, 0x96, 125);
	int ok = 1;
	for (int i = 0; i < 125; i++)
		if ((unsigned char)buf[i] != 0x96) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_60: memset pattern");
	memset(buf, 0, 125);
	ok = 1;
	for (int i = 0; i < 125; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_60: memset zero");
	char src[125], dst[125];
	for (int i = 0; i < 125; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 125);
	KTEST_EQ(memcmp(src, dst, 125), 0, "fuzz_string_60: memcpy");
}

static void fuzz_kheap_61(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 61");
	static const size_t sizes[] = {1675, 8133, 1370, 3403, 1688, 1046, 1721, 2977, 234, 6137, 6523, 27, 5501, 2642, 6446, 866, 6910, 2741, 7488, 7367, 8185, 2290, 6208, 6608, 1586, 2784, 4214};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[27];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_61: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_61: all patterns intact");
}

static void fuzz_slab_62(void)
{
	KTEST_BEGIN("fuzz: slab scenario 62");
	struct kmem_cache *c = kmem_cache_create("fuzz-62", 248, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_62: cache created");
	void *objs[39];
	for (int i = 0; i < 39; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_62: alloc");
		memset(objs[i], 0x12, 248);
	}
	int ok = 1;
	for (int i = 0; i < 39; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 248; j++)
			if (p[j] != 0x12) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_62: patterns intact");
	for (int i = 0; i < 39; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_63(void)
{
	KTEST_BEGIN("fuzz: slab scenario 63");
	struct kmem_cache *c = kmem_cache_create("fuzz-63", 284, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_63: cache created");
	void *objs[25];
	for (int i = 0; i < 25; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_63: alloc");
		memset(objs[i], 0x9A, 284);
	}
	int ok = 1;
	for (int i = 0; i < 25; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 284; j++)
			if (p[j] != 0x9A) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_63: patterns intact");
	for (int i = 0; i < 25; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_pmm_64(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 64");
	size_t before = pmm_free_pages_count();
	void *pages[13];
	int ok = 1;
	for (int i = 0; i < 13; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_64: all allocs succeeded");
	for (int i = 0; i < 13; i += 2)
		pmm_free_pages(pages[i], 0);
	for (int i = 1; i < 13; i += 2)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_64: zero leak");
}

static void fuzz_kheap_65(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 65");
	static const size_t sizes[] = {8146, 5683, 7071, 2921, 7183, 4473, 464, 6959, 1479, 1878, 6317, 7524, 5066, 3742, 4013, 3611, 6988, 2334, 176, 7528};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[20];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_65: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_65: all patterns intact");
}

static void fuzz_kheap_66(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 66");
	static const size_t sizes[] = {4659, 3682, 943, 3178, 4989, 7501, 7970, 1883, 900, 6581, 7035, 7199, 7856, 4044, 263, 3745, 7315, 6221, 6097, 42, 4110, 1035, 4429, 6858, 2964, 2001, 4735, 6514, 5267, 3228, 2023, 2258, 6205, 1210, 1491};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[35];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_66: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_66: all patterns intact");
}

static void fuzz_slab_67(void)
{
	KTEST_BEGIN("fuzz: slab scenario 67");
	struct kmem_cache *c = kmem_cache_create("fuzz-67", 109, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_67: cache created");
	void *objs[28];
	for (int i = 0; i < 28; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_67: alloc");
		memset(objs[i], 0x0E, 109);
	}
	int ok = 1;
	for (int i = 0; i < 28; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 109; j++)
			if (p[j] != 0x0E) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_67: patterns intact");
	for (int i = 0; i < 28; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_string_68(void)
{
	KTEST_BEGIN("fuzz: string scenario 68");
	char buf[89];
	memset(buf, 0x74, 89);
	int ok = 1;
	for (int i = 0; i < 89; i++)
		if ((unsigned char)buf[i] != 0x74) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_68: memset pattern");
	memset(buf, 0, 89);
	ok = 1;
	for (int i = 0; i < 89; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_68: memset zero");
	char src[89], dst[89];
	for (int i = 0; i < 89; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 89);
	KTEST_EQ(memcmp(src, dst, 89), 0, "fuzz_string_68: memcpy");
}

static void fuzz_string_69(void)
{
	KTEST_BEGIN("fuzz: string scenario 69");
	char buf[69];
	memset(buf, 0x68, 69);
	int ok = 1;
	for (int i = 0; i < 69; i++)
		if ((unsigned char)buf[i] != 0x68) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_69: memset pattern");
	memset(buf, 0, 69);
	ok = 1;
	for (int i = 0; i < 69; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_69: memset zero");
	char src[69], dst[69];
	for (int i = 0; i < 69; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 69);
	KTEST_EQ(memcmp(src, dst, 69), 0, "fuzz_string_69: memcpy");
}

static void fuzz_pmm_70(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 70");
	size_t before = pmm_free_pages_count();
	void *pages[23];
	int ok = 1;
	for (int i = 0; i < 23; i++) {
		pages[i] = pmm_alloc_pages(4);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_70: all allocs succeeded");
	for (int i = 23 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 4);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_70: zero leak");
}

static void fuzz_string_71(void)
{
	KTEST_BEGIN("fuzz: string scenario 71");
	char buf[125];
	memset(buf, 0xD8, 125);
	int ok = 1;
	for (int i = 0; i < 125; i++)
		if ((unsigned char)buf[i] != 0xD8) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_71: memset pattern");
	memset(buf, 0, 125);
	ok = 1;
	for (int i = 0; i < 125; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_71: memset zero");
	char src[125], dst[125];
	for (int i = 0; i < 125; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 125);
	KTEST_EQ(memcmp(src, dst, 125), 0, "fuzz_string_71: memcpy");
}

static void fuzz_pmm_72(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 72");
	size_t before = pmm_free_pages_count();
	void *pages[31];
	int ok = 1;
	for (int i = 0; i < 31; i++) {
		pages[i] = pmm_alloc_pages(2);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_72: all allocs succeeded");
	for (int i = 0; i < 31; i++)
		pmm_free_pages(pages[i], 2);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_72: zero leak");
}

static void fuzz_math_73(void)
{
	KTEST_BEGIN("fuzz: math scenario 73");
	long long a = 600521LL, b = 666942LL;
	KTEST_EQ(a + b, 1267463LL, "fuzz_math_73: add");
	KTEST_EQ(a - b, -66421LL, "fuzz_math_73: sub");
	KTEST_EQ(a * b, 400512676782LL, "fuzz_math_73: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_73: div");
	KTEST_EQ(a % b, 600521LL, "fuzz_math_73: mod");
}

static void fuzz_kheap_74(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 74");
	static const size_t sizes[] = {3493, 5249, 7482, 361, 6393, 7185, 6232, 27, 135, 3273, 3989, 189, 5128, 432, 1812, 6269, 5023, 6328, 4547, 5350, 4705, 3192, 4517, 2827, 5083, 2758, 5578, 290, 4024, 5697, 3467};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[31];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_74: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_74: all patterns intact");
}

static void fuzz_kheap_75(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 75");
	static const size_t sizes[] = {1082, 3453, 1766, 4281, 1198, 2432, 1659, 1306, 1648, 5143, 2474, 425, 5160, 6660, 1014, 7839};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[16];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_75: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_75: all patterns intact");
}

static void fuzz_math_76(void)
{
	KTEST_BEGIN("fuzz: math scenario 76");
	long long a = 663682LL, b = 112402LL;
	KTEST_EQ(a + b, 776084LL, "fuzz_math_76: add");
	KTEST_EQ(a - b, 551280LL, "fuzz_math_76: sub");
	KTEST_EQ(a * b, 74599184164LL, "fuzz_math_76: mul");
	KTEST_EQ(a / b, 5LL, "fuzz_math_76: div");
	KTEST_EQ(a % b, 101672LL, "fuzz_math_76: mod");
}

static void fuzz_pmm_77(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 77");
	size_t before = pmm_free_pages_count();
	void *pages[2];
	int ok = 1;
	for (int i = 0; i < 2; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_77: all allocs succeeded");
	for (int i = 2 - 1; i >= 0; i--)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_77: zero leak");
}

static void fuzz_string_78(void)
{
	KTEST_BEGIN("fuzz: string scenario 78");
	char buf[42];
	memset(buf, 0x16, 42);
	int ok = 1;
	for (int i = 0; i < 42; i++)
		if ((unsigned char)buf[i] != 0x16) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_78: memset pattern");
	memset(buf, 0, 42);
	ok = 1;
	for (int i = 0; i < 42; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_78: memset zero");
	char src[42], dst[42];
	for (int i = 0; i < 42; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 42);
	KTEST_EQ(memcmp(src, dst, 42), 0, "fuzz_string_78: memcpy");
}

static void fuzz_pmm_79(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 79");
	size_t before = pmm_free_pages_count();
	void *pages[3];
	int ok = 1;
	for (int i = 0; i < 3; i++) {
		pages[i] = pmm_alloc_pages(3);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_79: all allocs succeeded");
	for (int i = 0; i < 3; i += 2)
		pmm_free_pages(pages[i], 3);
	for (int i = 1; i < 3; i += 2)
		pmm_free_pages(pages[i], 3);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_79: zero leak");
}

static void fuzz_pmm_80(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 80");
	size_t before = pmm_free_pages_count();
	void *pages[13];
	int ok = 1;
	for (int i = 0; i < 13; i++) {
		pages[i] = pmm_alloc_pages(2);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_80: all allocs succeeded");
	for (int i = 0; i < 13; i++)
		pmm_free_pages(pages[i], 2);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_80: zero leak");
}

static void fuzz_slab_81(void)
{
	KTEST_BEGIN("fuzz: slab scenario 81");
	struct kmem_cache *c = kmem_cache_create("fuzz-81", 93, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_81: cache created");
	void *objs[15];
	for (int i = 0; i < 15; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_81: alloc");
		memset(objs[i], 0x2E, 93);
	}
	int ok = 1;
	for (int i = 0; i < 15; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 93; j++)
			if (p[j] != 0x2E) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_81: patterns intact");
	for (int i = 0; i < 15; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_pmm_82(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 82");
	size_t before = pmm_free_pages_count();
	void *pages[20];
	int ok = 1;
	for (int i = 0; i < 20; i++) {
		pages[i] = pmm_alloc_pages(1);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_82: all allocs succeeded");
	for (int i = 0; i < 20; i += 2)
		pmm_free_pages(pages[i], 1);
	for (int i = 1; i < 20; i += 2)
		pmm_free_pages(pages[i], 1);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_82: zero leak");
}

static void fuzz_pmm_83(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 83");
	size_t before = pmm_free_pages_count();
	void *pages[5];
	int ok = 1;
	for (int i = 0; i < 5; i++) {
		pages[i] = pmm_alloc_pages(3);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_83: all allocs succeeded");
	for (int i = 0; i < 5; i++)
		pmm_free_pages(pages[i], 3);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_83: zero leak");
}

static void fuzz_kheap_84(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 84");
	static const size_t sizes[] = {1756, 4296, 6640, 2009, 1479, 2420, 5771, 990, 5284, 3528, 3631, 2409, 4478, 5687, 8071, 2808, 6919, 1220, 6163, 107, 8084, 312, 2899, 5169, 2062, 5363, 1531, 5103, 2076, 2334, 4889};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[31];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_84: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_84: all patterns intact");
}

static void fuzz_string_85(void)
{
	KTEST_BEGIN("fuzz: string scenario 85");
	char buf[32];
	memset(buf, 0xD2, 32);
	int ok = 1;
	for (int i = 0; i < 32; i++)
		if ((unsigned char)buf[i] != 0xD2) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_85: memset pattern");
	memset(buf, 0, 32);
	ok = 1;
	for (int i = 0; i < 32; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_85: memset zero");
	char src[32], dst[32];
	for (int i = 0; i < 32; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 32);
	KTEST_EQ(memcmp(src, dst, 32), 0, "fuzz_string_85: memcpy");
}

static void fuzz_math_86(void)
{
	KTEST_BEGIN("fuzz: math scenario 86");
	long long a = 6715LL, b = 779071LL;
	KTEST_EQ(a + b, 785786LL, "fuzz_math_86: add");
	KTEST_EQ(a - b, -772356LL, "fuzz_math_86: sub");
	KTEST_EQ(a * b, 5231461765LL, "fuzz_math_86: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_86: div");
	KTEST_EQ(a % b, 6715LL, "fuzz_math_86: mod");
}

static void fuzz_slab_87(void)
{
	KTEST_BEGIN("fuzz: slab scenario 87");
	struct kmem_cache *c = kmem_cache_create("fuzz-87", 148, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_87: cache created");
	void *objs[51];
	for (int i = 0; i < 51; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_87: alloc");
		memset(objs[i], 0xAD, 148);
	}
	int ok = 1;
	for (int i = 0; i < 51; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 148; j++)
			if (p[j] != 0xAD) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_87: patterns intact");
	for (int i = 0; i < 51; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_88(void)
{
	KTEST_BEGIN("fuzz: slab scenario 88");
	struct kmem_cache *c = kmem_cache_create("fuzz-88", 382, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_88: cache created");
	void *objs[62];
	for (int i = 0; i < 62; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_88: alloc");
		memset(objs[i], 0x94, 382);
	}
	int ok = 1;
	for (int i = 0; i < 62; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 382; j++)
			if (p[j] != 0x94) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_88: patterns intact");
	for (int i = 0; i < 62; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_string_89(void)
{
	KTEST_BEGIN("fuzz: string scenario 89");
	char buf[112];
	memset(buf, 0x3F, 112);
	int ok = 1;
	for (int i = 0; i < 112; i++)
		if ((unsigned char)buf[i] != 0x3F) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_89: memset pattern");
	memset(buf, 0, 112);
	ok = 1;
	for (int i = 0; i < 112; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_89: memset zero");
	char src[112], dst[112];
	for (int i = 0; i < 112; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 112);
	KTEST_EQ(memcmp(src, dst, 112), 0, "fuzz_string_89: memcpy");
}

static void fuzz_string_90(void)
{
	KTEST_BEGIN("fuzz: string scenario 90");
	char buf[100];
	memset(buf, 0xC9, 100);
	int ok = 1;
	for (int i = 0; i < 100; i++)
		if ((unsigned char)buf[i] != 0xC9) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_90: memset pattern");
	memset(buf, 0, 100);
	ok = 1;
	for (int i = 0; i < 100; i++)
		if (buf[i] != 0) ok = 0;
	KTEST_TRUE(ok, "fuzz_string_90: memset zero");
	char src[100], dst[100];
	for (int i = 0; i < 100; i++) src[i] = (char)(i & 0x7F);
	memcpy(dst, src, 100);
	KTEST_EQ(memcmp(src, dst, 100), 0, "fuzz_string_90: memcpy");
}

static void fuzz_pmm_91(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 91");
	size_t before = pmm_free_pages_count();
	void *pages[11];
	int ok = 1;
	for (int i = 0; i < 11; i++) {
		pages[i] = pmm_alloc_pages(2);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_91: all allocs succeeded");
	for (int i = 0; i < 11; i++)
		pmm_free_pages(pages[i], 2);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_91: zero leak");
}

static void fuzz_slab_92(void)
{
	KTEST_BEGIN("fuzz: slab scenario 92");
	struct kmem_cache *c = kmem_cache_create("fuzz-92", 174, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_92: cache created");
	void *objs[58];
	for (int i = 0; i < 58; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_92: alloc");
		memset(objs[i], 0x2E, 174);
	}
	int ok = 1;
	for (int i = 0; i < 58; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 174; j++)
			if (p[j] != 0x2E) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_92: patterns intact");
	for (int i = 0; i < 58; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_math_93(void)
{
	KTEST_BEGIN("fuzz: math scenario 93");
	long long a = 77061LL, b = 623135LL;
	KTEST_EQ(a + b, 700196LL, "fuzz_math_93: add");
	KTEST_EQ(a - b, -546074LL, "fuzz_math_93: sub");
	KTEST_EQ(a * b, 48019406235LL, "fuzz_math_93: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_93: div");
	KTEST_EQ(a % b, 77061LL, "fuzz_math_93: mod");
}

static void fuzz_math_94(void)
{
	KTEST_BEGIN("fuzz: math scenario 94");
	long long a = 567159LL, b = 708516LL;
	KTEST_EQ(a + b, 1275675LL, "fuzz_math_94: add");
	KTEST_EQ(a - b, -141357LL, "fuzz_math_94: sub");
	KTEST_EQ(a * b, 401841226044LL, "fuzz_math_94: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_94: div");
	KTEST_EQ(a % b, 567159LL, "fuzz_math_94: mod");
}

static void fuzz_kheap_95(void)
{
	KTEST_BEGIN("fuzz: kheap scenario 95");
	static const size_t sizes[] = {2142, 7742, 6999, 6164, 5605, 110, 7736, 2346, 7499, 5338, 5824, 4364, 7642, 6000, 7251, 6087, 7958, 280, 1548, 4414, 6894, 1925, 7880, 4915, 7464, 5862};
	int count = (int)(sizeof(sizes) / sizeof(sizes[0]));
	void *ptrs[26];
	for (int i = 0; i < count; i++) {
		ptrs[i] = kmalloc(sizes[i]);
		KTEST_NOT_NULL(ptrs[i], "fuzz_kheap_95: alloc");
		memset(ptrs[i], (int)(i & 0xFF), sizes[i]);
	}
	int ok = 1;
	for (int i = 0; i < count; i++) {
		uint8_t *p = ptrs[i];
		for (size_t j = 0; j < sizes[i]; j++)
			if (p[j] != (uint8_t)(i & 0xFF)) ok = 0;
		kfree(ptrs[i]);
	}
	KTEST_TRUE(ok, "fuzz_kheap_95: all patterns intact");
}

static void fuzz_slab_96(void)
{
	KTEST_BEGIN("fuzz: slab scenario 96");
	struct kmem_cache *c = kmem_cache_create("fuzz-96", 12, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_96: cache created");
	void *objs[34];
	for (int i = 0; i < 34; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_96: alloc");
		memset(objs[i], 0xD5, 12);
	}
	int ok = 1;
	for (int i = 0; i < 34; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 12; j++)
			if (p[j] != 0xD5) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_96: patterns intact");
	for (int i = 0; i < 34; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_slab_97(void)
{
	KTEST_BEGIN("fuzz: slab scenario 97");
	struct kmem_cache *c = kmem_cache_create("fuzz-97", 489, NULL, NULL);
	KTEST_NOT_NULL(c, "fuzz_slab_97: cache created");
	void *objs[44];
	for (int i = 0; i < 44; i++) {
		objs[i] = kmem_cache_alloc(c);
		KTEST_NOT_NULL(objs[i], "fuzz_slab_97: alloc");
		memset(objs[i], 0xD7, 489);
	}
	int ok = 1;
	for (int i = 0; i < 44; i++) {
		uint8_t *p = objs[i];
		for (int j = 0; j < 489; j++)
			if (p[j] != 0xD7) ok = 0;
	}
	KTEST_TRUE(ok, "fuzz_slab_97: patterns intact");
	for (int i = 0; i < 44; i++)
		kmem_cache_free(c, objs[i]);
}

static void fuzz_math_98(void)
{
	KTEST_BEGIN("fuzz: math scenario 98");
	long long a = 389515LL, b = 487017LL;
	KTEST_EQ(a + b, 876532LL, "fuzz_math_98: add");
	KTEST_EQ(a - b, -97502LL, "fuzz_math_98: sub");
	KTEST_EQ(a * b, 189700426755LL, "fuzz_math_98: mul");
	KTEST_EQ(a / b, 0LL, "fuzz_math_98: div");
	KTEST_EQ(a % b, 389515LL, "fuzz_math_98: mod");
}

static void fuzz_pmm_99(void)
{
	KTEST_BEGIN("fuzz: PMM scenario 99");
	size_t before = pmm_free_pages_count();
	void *pages[18];
	int ok = 1;
	for (int i = 0; i < 18; i++) {
		pages[i] = pmm_alloc_pages(0);
		if (!pages[i]) { ok = 0; break; }
	}
	KTEST_TRUE(ok, "fuzz_pmm_99: all allocs succeeded");
	for (int i = 0; i < 18; i++)
		pmm_free_pages(pages[i], 0);
	KTEST_EQ(pmm_free_pages_count(), before, "fuzz_pmm_99: zero leak");
}

KTEST_REGISTER(ktest_fuzz, "fuzz: generated scenarios", KTEST_CAT_BOOT)
static void ktest_fuzz(void)
{
	KTEST_BEGIN("fuzz: generated scenarios");
	fuzz_slab_0();
	fuzz_kheap_1();
	fuzz_kheap_2();
	fuzz_pmm_3();
	fuzz_slab_4();
	fuzz_kheap_5();
	fuzz_pmm_6();
	fuzz_string_7();
	fuzz_kheap_8();
	fuzz_slab_9();
	fuzz_kheap_10();
	fuzz_string_11();
	fuzz_math_12();
	fuzz_pmm_13();
	fuzz_slab_14();
	fuzz_pmm_15();
	fuzz_slab_16();
	fuzz_kheap_17();
	fuzz_string_18();
	fuzz_pmm_19();
	fuzz_slab_20();
	fuzz_kheap_21();
	fuzz_math_22();
	fuzz_slab_23();
	fuzz_slab_24();
	fuzz_math_25();
	fuzz_slab_26();
	fuzz_slab_27();
	fuzz_pmm_28();
	fuzz_pmm_29();
	fuzz_slab_30();
	fuzz_kheap_31();
	fuzz_string_32();
	fuzz_pmm_33();
	fuzz_pmm_34();
	fuzz_slab_35();
	fuzz_pmm_36();
	fuzz_kheap_37();
	fuzz_kheap_38();
	fuzz_pmm_39();
	fuzz_slab_40();
	fuzz_math_41();
	fuzz_pmm_42();
	fuzz_kheap_43();
	fuzz_string_44();
	fuzz_pmm_45();
	fuzz_string_46();
	fuzz_string_47();
	fuzz_kheap_48();
	fuzz_slab_49();
	fuzz_kheap_50();
	fuzz_kheap_51();
	fuzz_math_52();
	fuzz_pmm_53();
	fuzz_slab_54();
	fuzz_slab_55();
	fuzz_kheap_56();
	fuzz_math_57();
	fuzz_string_58();
	fuzz_string_59();
	fuzz_string_60();
	fuzz_kheap_61();
	fuzz_slab_62();
	fuzz_slab_63();
	fuzz_pmm_64();
	fuzz_kheap_65();
	fuzz_kheap_66();
	fuzz_slab_67();
	fuzz_string_68();
	fuzz_string_69();
	fuzz_pmm_70();
	fuzz_string_71();
	fuzz_pmm_72();
	fuzz_math_73();
	fuzz_kheap_74();
	fuzz_kheap_75();
	fuzz_math_76();
	fuzz_pmm_77();
	fuzz_string_78();
	fuzz_pmm_79();
	fuzz_pmm_80();
	fuzz_slab_81();
	fuzz_pmm_82();
	fuzz_pmm_83();
	fuzz_kheap_84();
	fuzz_string_85();
	fuzz_math_86();
	fuzz_slab_87();
	fuzz_slab_88();
	fuzz_string_89();
	fuzz_string_90();
	fuzz_pmm_91();
	fuzz_slab_92();
	fuzz_math_93();
	fuzz_math_94();
	fuzz_kheap_95();
	fuzz_slab_96();
	fuzz_slab_97();
	fuzz_math_98();
	fuzz_pmm_99();
}
